### ISSUE TITLE
[macOS-chrome-1920px] 8주차 QA진행

### ISSUE THREAD

**Issue by bakgom123** [100-hours-a-week/2-yuni-jeong-community-be#41]
**버그 설명**
 - [x] 100-hours-a-week/2-yuni-jeong-community-fe#38
<img width="718" alt="스크린샷 2024-12-18 오후 1 57 39" src="https://github.com/user-attachments/assets/d5ee20d0-3c67-4374-9c9e-205eab0a977a" />
<img width="628" alt="스크린샷 2024-12-18 오후 1 58 18" src="https://github.com/user-attachments/assets/5f750f3d-c072-4c7b-977a-3678365df272" />

 - [x] 100-hours-a-week/2-yuni-jeong-community-fe#41
<img width="661" alt="스크린샷 2024-12-18 오후 1 59 55" src="https://github.com/user-attachments/assets/4b564457-d797-4741-9619-cbf224531d09" />

 - [x] 100-hours-a-week/2-yuni-jeong-community-fe#64
<img width="662" alt="스크린샷 2024-12-18 오후 2 02 11" src="https://github.com/user-attachments/assets/aae5da71-2a39-49c2-bd58-03c9515e99d4" />

 - [x] 100-hours-a-week/2-yuni-jeong-community-fe#43
<img width="712" alt="스크린샷 2024-12-18 오후 2 05 49" src="https://github.com/user-attachments/assets/6a435f00-4a84-47b6-a368-f722216c8562" />

 - [x] 100-hours-a-week/2-yuni-jeong-community-fe#54
https://github.com/user-attachments/assets/8de738c7-c75a-451e-b143-037bd7aca76e

**데스크톱(다음 정보를 작성해 주세요):**
- OS: macOS
- Browser: Chrome

**추가적인 내용:**
혹시 제가 만든 이슈에 대해서 궁금하신 점이 있으시다면 언제든 편하게 말씀주세요!

**Comment by bakgom123** [comment]
3번의 경우 과제의 요구사항에는 맞는 것 같은데 만약 프로필 사진만 변경을 원한다면 닉네임을 다시 똑같이 쳐야하는 불편함과 반대로 닉네임만 변경을 원한다면 프로필을 다시 업로드하는 과정이 불편한 것 같습니다.
