### ISSUE TITLE
[Mac-Chrome] QA - hyuk

### ISSUE THREAD

**Issue by duckchanahn** [100-hours-a-week/2-yuni-jeong-community-be#42]
**버그 설명**
- [x] 100-hours-a-week/2-yuni-jeong-community-fe#62
- [x] 100-hours-a-week/2-yuni-jeong-community-fe#63
- [x] 100-hours-a-week/2-yuni-jeong-community-fe#56
- [x] 100-hours-a-week/2-yuni-jeong-community-be#46

**데스크톱:**
 - Device: MacBook Pro
 - OS: Mac
 - Browser chrome
